## **Boosting:**

In [ ]:
import pandas as pd
data = pd.read_csv('/content/sample_data/train.csv')
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
data = data[['Pclass', 'Age', 'SibSp','Fare', 'Survived']]
data.dropna(inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    714 non-null    int64  
 1   Age       714 non-null    float64
 2   SibSp     714 non-null    int64  
 3   Fare      714 non-null    float64
 4   Survived  714 non-null    int64  
dtypes: float64(2), int64(3)
memory usage: 33.5 KB


<ipython-input-14-14ff195a21cc>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace = True)


In [ ]:
x = data[[ 'Pclass', 'Age', 'SibSp','Fare']]
y = data['Survived']

In [ ]:
x[:5]

Pclass   Age  SibSp     Fare
0       3  22.0      1   7.2500
1       1  38.0      1  71.2833
2       3  26.0      0   7.9250
3       1  35.0      1  53.1000
4       3  35.0      0   8.0500

In [ ]:
y[:5]

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.15, random_state=10)
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape)

(606, 4) (108, 4) (606,) (108,)


## **AdaBoost Method : **

In [ ]:
from sklearn.ensemble import AdaBoostClassifier,  GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

abc = AdaBoostClassifier(n_estimators = 20,base_estimator=LogisticRegression(), learning_rate=1)
abc.fit(xtrain, ytrain)
ypreds = abc.predict(xtest)
print(accuracy_score(ypreds,ytest))

0.7407407407407407


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


## **Gradient Boost : **

In [ ]:
gbc = GradientBoostingClassifier(n_estimators = 20,max_depth=1, learning_rate=1)      #GradientBoostClassifier doesnot take base_estimator as it uses DT by default.
gbc.fit(xtrain, ytrain)
ypreds = gbc.predict(xtest)
print(accuracy_score(ypreds,ytest))

0.7129629629629629


## **Stacking :**

In [1]:
from sklearn.datasets import make_classification
x, y = make_classification(n_samples=1000, n_features=5, random_state =1)

In [2]:
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [3]:
x[:5]

array([[-1.39087601,  0.62478042,  3.4809096 ,  2.3823372 ,  0.38622388],
       [-0.48529475,  0.30051483,  1.33915253,  0.84620081,  1.17745439],
       [-0.73504687,  0.13412273,  1.54350554,  1.22343943, -0.62879943],
       [ 0.6594484 ,  1.47747999,  1.0281535 , -0.80770875, -0.34350003],
       [ 0.17288184,  0.99271923,  1.18375139, -0.10191134,  0.08911753]])

In [4]:
y[:5]

array([1, 1, 1, 1, 0])

In [6]:
import numpy as np
np.unique(y)            # Binary Classification dataset with 5 features

array([0, 1])

In [12]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=0.2, random_state = 1)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

level0 = [
    ('lr', LogisticRegression()),
    ('dt', DecisionTreeClassifier()),
    ('svc', SVC())
]

level1 = LogisticRegression()


In [17]:
from sklearn.ensemble import StackingClassifier
model = StackingClassifier(estimators=level0, final_estimator=level1)
model.fit(xtrain,ytrain)


StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('svc', SVC())],
                   final_estimator=LogisticRegression())

In [20]:
ypreds = model.predict(xtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(ypreds, ytest))

0.855


In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

level0 = [
    ('lr', LogisticRegression()),
    ('dt', DecisionTreeClassifier()),
    ('svc', SVC())
]

# level1 = [
#     ('lr1', LogisticRegression()),
#     ('nb', GaussianNB())
# ]
level2 = DecisionTreeClassifier()


from sklearn.ensemble import StackingClassifier
model = StackingClassifier(estimators=level0, final_estimator=level2)
model.fit(xtrain,ytrain)

ypreds = model.predict(xtest)
from sklearn.metrics import accuracy_score
print(accuracy_score(ypreds, ytest))


0.79
