In [ ]:
from sklearn.datasets import load_iris

In [ ]:
data = load_iris()
x = data.data
y = data.target

In [ ]:
print(x.shape, y.shape)

(150, 4) (150,)


In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size =0.2, random_state = 1)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(xtrain,ytrain)
ypreds = model.predict(xtest)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
from sklearn.metrics import accuracy_score
print('Test Accuracy = ', accuracy_score(ypreds,ytest))

Test Accuracy =  0.9666666666666667


In [ ]:
train_preds = model.predict(xtrain)
print('Train Accuracy = ', accuracy_score(train_preds, ytrain))

Train Accuracy =  0.9833333333333333


## K Fold Cross Validation ::

In [ ]:
from sklearn.model_selection import KFold, cross_val_score
kf = KFold(n_splits = 5)
score = cross_val_score(LogisticRegression(),x,y, cv = kf)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [ ]:
print(score)

[1.         1.         0.86666667 0.93333333 0.83333333]


In [ ]:
score.mean()

0.9266666666666665

In [ ]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [ ]:
print(len(y[y==0]),len(y[y==1]),len(y[y==2]))

50 50 50


## Case 2

In [1]:
from sklearn.datasets import load_iris
data = load_iris()
x = data.data
y = data.target
print(x.shape,y.shape)

(150, 4) (150,)


In [2]:
type(y)

numpy.ndarray

In [3]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2])

In [6]:
# Split
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain,ytest = train_test_split(x,y, test_size=0.3, random_state=1)
print(xtrain.shape, xtest.shape)

(105, 4) (45, 4)


In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
model = LogisticRegression()
model.fit(xtrain, ytrain)
ypreds = model.predict(xtest)
print(accuracy_score(ypreds,ytest))

0.9777777777777777


Apply K-Fold

In [9]:
from sklearn.model_selection import KFold, cross_val_score
kf = KFold(n_splits=5)
score = cross_val_score(LogisticRegression(), x, y,cv=kf)
print(score)
print(score.mean())

[1.         1.         0.86666667 0.93333333 0.83333333]
0.9266666666666665


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

Apply Stratified for the same dataset.

In [10]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 5)
score = cross_val_score(LogisticRegression(), x, y,cv=skf)
print(score)
print(score.mean())

[0.96666667 1.         0.93333333 0.96666667 1.        ]
0.9733333333333334


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


# Stratified Cross Fold ::
  For unbalanced datasets.

In [ ]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 5)
scores = cross_val_score(LogisticRegression(),x,y, cv = skf)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
print(score)

[1.         1.         0.86666667 0.93333333 0.83333333]


In [ ]:
score.mean()

0.9266666666666665