# **Linear Regression ::**



In [37]:
import pandas as pd
data = pd.read_csv('/content/sample_data/Housing.csv')
print(data.shape)
print(data.columns)

(545, 13)
Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')


In [38]:
# For simplicity we'll take few columns only

x = data[['bedrooms', 'bathrooms']].head(100)
x.shape

(100, 2)

In [39]:
import numpy as np
x.insert(0, 'bias', np.ones(100))
x.head()

bias  bedrooms  bathrooms
0   1.0         4          2
1   1.0         4          4
2   1.0         3          2
3   1.0         4          2
4   1.0         4          1

In [40]:
y = data['price'].head(100)
y.shape

(100,)

In [41]:
import numpy as np

x = x.values    #Converted into Array
y = y.values

In [42]:
# Matrix multi is using dot() & inverse is using inv()
paras = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)

In [43]:
print('w0 w1 w2 w3 ' ,paras)

w0 w1 w2 w3  [4994912.32328774  539030.20064244  607591.76623461]


predicted values = h(x) = 4.24 + 139* area + 48348 * bedrooms + 59011 * bathrooms

In [44]:
# reshape y as 100,1
y= y.reshape((100,1))
print(y.shape)

(100, 1)


In [45]:
w = np.zeros((x.shape[1],1))

In [46]:
def gd(x,y,alpha = 0.001, iters = 100):       #Alpha & iters arethe default parameters.
  w = np.zeros((x.shape[1],1))
  for i in range(iters):
    error =  y - x.dot(w)     # ypred = x*W
    grad = -(x.T).dot(error)
    w = w - alpha * grad
  return w



In [47]:
w = gd(x,y)
w


array([[1645914.29834519],
       [1402072.88407835],
       [ 821378.30885241]])

In [48]:
x = data[['area', 'bedrooms', 'bathrooms']].head(100)

In [50]:
import numpy as np
x.insert(0, 'bias', np.ones(100))
x.head()

bias  area  bedrooms  bathrooms
0   1.0  7420         4          2
1   1.0  8960         4          4
2   1.0  9960         3          2
3   1.0  7500         4          2
4   1.0  7420         4          1

In [51]:
from sklearn.preprocessing import MinMaxScaler    #Used for normalization
scaler = MinMaxScaler()     # Scaling returns Array
x_scaled = scaler.fit_transform(x)
x_scaled[:5]

array([[0.        , 0.30866142, 0.66666667, 0.33333333],
       [0.        , 0.42992126, 0.66666667, 1.        ],
       [0.        , 0.50866142, 0.33333333, 0.33333333],
       [0.        , 0.31496063, 0.66666667, 0.33333333],
       [0.        , 0.30866142, 0.66666667, 0.        ]])

In [52]:
gd(x_scaled,y)

array([[      0.        ],
       [6068448.88325941],
       [8960685.51376968],
       [5014421.56210476]])

In [54]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(x_scaled,y)
model.coef_


array([[      0.        , 1766036.60707027, 1450464.48014385,
        1770333.4304306 ]])

In [55]:
gd(x_scaled, y, 0.01, 150)

array([[      0.        ],
       [8302176.613939  ],
       [8489607.03944557],
       [4137600.12642684]])

Simple Regression (one Feature)::

In [49]:
x = x[:,[0,1]]
x[:5]

InvalidIndexError: ignored

In [ ]:
# Matrix multi is using dot() & inverse is using inv()
paras = np.linalg.inv(x.T.dot(x)).dot(x.T).dot(y)

In [ ]:
print('w0 w1 ' ,paras)